Terraform 1
Otus-DevOps-2021-08/Alex2421_infra pull request #11
Opened 2021-12-04 09:24 UTC by Alex2421

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-12-05 19:49 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз, оставил отметку к файлу.
Так же стоит обратить вниманием на блок объявления провайдера.
ДЗ возвращаю на доработку =)

2021-12-05 19:49 UTC, mrgreyves commented on terraform/variables.tf
> +ariable cloud_id {
Ошибочка =)

2021-12-06 08:01 UTC, Alex2421 commented on terraform/variables.tf
> +ariable cloud_id {
Добрый день! Исправил. В variables добавил букву в main добавил переменные вместо значений оставил только token.

2021-12-06 08:06 UTC, Alex2421 commented on terraform/variables.tf
> +ariable cloud_id {
Разобрался с Packer  у меня была ошибка не создавался образ для выполнения следующих ДЗ. Оказалось, что был исчерпан лимит на создание сетей. Удалил лишнюю и все заработало.

2021-12-07 11:35 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!
Ошибка в тестах связана с тем что в одно время в терраформе изменили порядок определение провайдеров =)

2021-12-07 15:26 UTC, merged