Cloud testapp
Otus-DevOps-2021-08/Alex2421_infra pull request #6
Opened 2021-09-21 13:26 UTC by Alex2421

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-09-23 09:06 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Вам стоит ознакомиться с результатами тестов, там много красного. Надо поправить скрипты и добавить в ридми адреса инстанса с приложением. ДЗ возвращаю на доработку.

2021-09-23 10:07 UTC, Alex2421 commented
Спасибо! Займусь.

2021-09-24 09:24 UTC, mrgreyves requested changes
Здравствуйте!)
Вам стоит снова обратить внимание на тесты, а именно на сообщения которые выделены красным цветом, например GA в тесте говорит что некоторые файлы не являются исполняемыми или что в некоторых файлах не хватает пустой строки в конце.
Нужно это подправить, дз снова возвращаю на доработку.

2021-10-02 10:33 UTC, mrgreyves requested changes
Здравствуйте!)
Снова смотрим на тесты. Скрипты снова не исполняемые, так же приложение не доступно. ДЗ возвращаю на доработку.

2021-10-06 09:25 UTC, mrgreyves requested changes
Ошибки все теже, смотрим мои предыдущие комментарии.

2021-10-06 20:03 UTC, Alex2421 commented
Про ошибки я знаю, пытаюсь исправить но работа все портит)) не могу понять почему файлы не исполняемые.

2021-10-19 18:22 UTC, mrgreyves requested changes
И снова результаты тестов =)

2021-10-22 09:50 UTC, mrgreyves requested changes
Здравствуйте!)
https://github.com/Otus-DevOps-2021-08/Alex2421_infra/runs/3963360724?check_suite_focus=true
Вот тут можно посмотреть результаты текущих тестов, к сожалению все не очень хорошо. ДЗ возвращаю на доработку

2021-11-03 17:07 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-11-03 19:54 UTC, Alex2421 commented
Подскажите, как мне смержить ветку теперь?

2021-12-02 20:14 UTC, closed without merging